---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: django-training
  description: Columbia University Information Technology training for Django REST Framework JSON:API
  annotations:
    # github.com/project-slug: columbia-it/django-jsonapi-training
    backstage.io/techdocs-ref: 'gitlab:https://gitlab.cc.columbia.edu:/ac45/django-training'
spec:
  type: service
  lifecycle: experimental
  owner: user:ac45
  consumesApis:
    - django-training-api
  providesApis:
    - django-training-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: django-training-api
  description: Demo of Django REST Framework JSON-API
  tags:
    - rest
spec:
  type: openapi
  lifecycle: development
  owner: user:ac45
  definition:
    $text: https://gitlab.cc.columbia.edu/ac45/django-training/blob/master/docs/schemas/openapi.yaml
